# Generated by Django 4.1.7 on 2023-05-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='verification_token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
