# Generated by Django 4.1.7 on 2023-04-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('phone', models.CharField(max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('other_cahrges', models.DecimalField(decimal_places=0.0, default=0.0, max_digits=50)),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'in process'), ('2', 'delivered')], max_length=50)),
                ('long', models.DecimalField(decimal_places=2, max_digits=50)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=50)),
                ('extra', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
    ]
