# Generated by Django 4.1.7 on 2023-04-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=50),
        ),
    ]
